// vue/src/components/converter-with-sources/converter-with-sources.vue
<template>
  <ConverterWithCalculator
    :availableExchangeRateSources="availableExchangeRateSources"
    :isLoading="isLoading"
    v-model:exchangeRatesSourceKey="exchangeRatesSourceKey"
    :availableCurrencies="availableCurrencies"
    :warningMessage="warningMessage"
    :defaultSourceCurrencyCharCode="defaultSourceCurrencyCharCode"
    :defaultTargetCurrencyCharCode="defaultTargetCurrencyCharCode"
  />
</template>

<script>
import ConverterWithCalculator from '../converter-with-calculator/converter-with-calculator.vue';

import rateSourcesManager from '../../api/exchange-sources/exchange-sources-manager.js'; // TODO: pass as props/context
import { Currency } from '../../api/exchange-sources/exchange-rates-data-objects.js';

export default {
  components: { ConverterWithCalculator },

  data() {
    return {
      availableCurrencies: [],
      warningMessage: null,
      isLoading: false,
      exchangeRatesSourceKey: 'cbr',
      availableExchangeRateSources: rateSourcesManager
        .getRegisteredSources()
        .map((item) => ({ key: item.key, caption: item.caption })),
      lastAbortController: null,
    };
  },

  computed: {
    defaultSourceCurrencyCharCode() {
      return Currency.USD().CharCode;
    },
    defaultTargetCurrencyCharCode() {
      return Currency.RUB().CharCode;
    },
  },

  methods: {},

  watch: {
    exchangeRatesSourceKey: {
      immediate: true,
      handler(newValue, _, onInvalidate) {
        this.isLoading = true;
        this.warningMessage = null;
        const currentAbortController = {};
        onInvalidate(() => (currentAbortController.aborted = true)); /* cancellationToken */
        rateSourcesManager
          .getRates(newValue)
          .then((exchangeRates) => {
            if (currentAbortController.aborted) {
              return;
            }
            this.availableCurrencies = exchangeRates?.Items;
            this.warningMessage = newValue === 'demo' ? 'Демо данные' : null;
            this.isLoading = false;
          })
          .catch((error) => {
            if (currentAbortController.aborted) {
              return;
            }
            const demoDataMessageTemplate =
              'При получении данных о курсе обмена валют возникла ошибка и показаны демонстрационные данные';
            this.isLoading = false;
            this.warningMessage = `${demoDataMessageTemplate} (${error})`;
            this.availableCurrencies = [Currency.RUB(), Currency.USD(), Currency.GBP()];
            this.sourceCurrencyCharCode = Currency.USD().CharCode;
            this.targetCurrencyCharCode = Currency.RUB().CharCode;
          });
      },
    },
  },
};
</script>

<style scoped></style>

// react/src/components/converter-with-sources/converter-with-sources.js
import { useEffect, useState, useCallback } from 'react';
import rateSourcesManager from '../../api/exchange-sources/exchange-sources-manager.js';
import ConverterWithCalculator from '../converter-with-calculator/converter-with-calculator.js';

import { Currency } from '../../api/exchange-sources/exchange-rates-data-objects';

function ConverterWithSources({ classes }) {
  const [isLoading, setIsLoading] = useState(true);
  const [availableCurrencies, setAvailableCurrencies] = useState([]);
  const [exchangeRatesSourceKey, setExchangeRatesSourceKey] = useState('cbr'); // default rates source, pass in props
  const [warningMessage, setWarningMessage] = useState();
  const [availableExchangeRateSources] = useState(
    rateSourcesManager.getRegisteredSources().map(item => ({ key: item.key, caption: item.caption })));


  useEffect(
    () => {
      setWarningMessage(undefined);
      setIsLoading(true);
      const currentAbortController = {};
      rateSourcesManager.getRates(exchangeRatesSourceKey)
        .then(exchangeRates => {
          if (currentAbortController.aborted) {
            return;
          }
          setAvailableCurrencies(exchangeRates?.Items);
          if (exchangeRatesSourceKey === 'demo') {
            setWarningMessage('Демо данные'); // move to rates, return with 'getRates'
          }
          else {
            setWarningMessage(undefined);
          }
          setIsLoading(false);
        })
        .catch(error => {
          if (currentAbortController.aborted) {
            return;
          }
          setIsLoading(false);
          const demoDataMessageTemplate = "При получении данных о курсе обмена валют возникла ошибка и показаны демонстрационные данные";
          setWarningMessage(`${demoDataMessageTemplate} (${error})`);
          setAvailableCurrencies([Currency.RUB(), Currency.USD(), Currency.GBP()]);
        });
      return () => currentAbortController.aborted = true; /* cancellationToken */
    },
    [exchangeRatesSourceKey]
  );

  const exchangeRatesSourceKeyChanged = useCallback(value => {
    setExchangeRatesSourceKey(value);
  }, []);

  return (
    <ConverterWithCalculator
      classes={ classes }
      availableExchangeRateSources={ availableExchangeRateSources }
      isLoading={ isLoading }
      exchangeRatesSourceKey={ exchangeRatesSourceKey }
      availableCurrencies={ availableCurrencies }
      warningMessage={ warningMessage }
      exchangeRatesSourceKeyChanged={ exchangeRatesSourceKeyChanged }
      defaultSourceCurrencyCharCode={ Currency.USD().CharCode }
      defaultTargetCurrencyCharCode={ Currency.RUB().CharCode }
    />
  );

}

export default ConverterWithSources;
