// react/src/components/currency-rate-expression/currency-rate-expression.js
import styles from './currency-rate-expression.module.css';
import styles__item from './__item/currency-rate-expression__item.module.css';

function CurrencyRateExpression({ sourceCurrencyCharCode, targetRate, targetCurrencyCharCode }) {
  return (
    <div className={ styles.s }>
      <p aria-label="Source rate" className={ styles__item.s }>1</p>
      <p aria-label="Source char code" className={ styles__item.s }>{ sourceCurrencyCharCode ?? 'USD' }</p>
      <p className={ styles__item.s }>=</p>
      <p aria-label="Target rate" className={ styles__item.s }>{ targetRate ?? '1' }</p>
      <p aria-label="Target char code" className={ styles__item.s }>{ targetCurrencyCharCode ?? 'RUB' }</p>
    </div>
  );
}

export default CurrencyRateExpression;

// vue/src/components/currency-rate-expression/currency-rate-expression.vue
<template>
  <div class="currency-rate-expression">
    <p class="currency-rate-expression__item" aria-label="Source rate">1</p>
    <p class="currency-rate-expression__item" aria-label="Source currency char code">{{ sourceCurrencyCharCode }}</p>
    <p class="currency-rate-expression__item">=</p>
    <p class="currency-rate-expression__item" aria-label="Target rate">{{ targetRate }}</p>
    <p class="currency-rate-expression__item" aria-label="Target currency char code">{{ targetCurrencyCharCode }}</p>
  </div>
</template>

<script>
export default {
  props: {
    sourceCurrencyCharCode: { type: String },
    targetRate: { type: Number },
    targetCurrencyCharCode: { type: String },
  },
};
</script>

<style>
.currency-rate-expression {
  margin-top: 20px;

  display: flex;
  justify-content: center;
  gap: 7px;

  font-style: normal;
  font-weight: 700;
  font-size: 20px;
}

.currency-rate-expression__item {
  /* reset browser styles */
  padding: 0;
  margin: 0;

  white-space: nowrap;
}
</style>
