// vue/src/components/converter.vue
<template>
  <div class="converter">
    <form @submit.prevent>
      <fieldset class="converter__values">
        <UiEditor tagName="input" v-model="amount" type="number" required :step="0.01" />
        <LabeledEditor caption="From">
          <UiEditor
            tagName="select"
            v-model="sourceCurrencyCharCode"
            required
            :listItems="availableCurrenciesListItems"
          />
        </LabeledEditor>
        <UiButton
          class="converter__currency-toggler"
          :image="toggleIconSrc"
          text="Toggle currencies"
          @click="() => handleTogglerClick()"
        />
        <LabeledEditor caption="To">
          <UiEditor
            tagName="select"
            v-model="targetCurrencyCharCode"
            required
            :listItems="availableCurrenciesListItems"
          />
        </LabeledEditor>
        <LabeledEditor caption="Exchange rates source">
          <UiEditor
            tagName="select"
            v-model="exchangeRatesSourceKey"
            required
            :listItems="availableExchangeRateSources"
          />
        </LabeledEditor>
      </fieldset>
    </form>
    <p class="converter__target-amount">{{ targetAmount }}</p>
    <CurrencyRateExpression
      :sourceCurrencyCharCode="sourceCurrencyCharCode"
      :targetRate="targetRate"
      :targetCurrencyCharCode="targetCurrencyCharCode"
    />
    <p v-if="demoDataMessage" class="converter__demo-data-message">{{ demoDataMessage }}</p>
    <LoadingPanel v-if="isLoading" />
  </div>
</template>

<script>
import UiEditor from './ui-editor.vue';
import LabeledEditor from './labeled-editor.vue';
import UiButton from './ui-button.vue';
import LoadingPanel from './loading-panel.vue';
import CurrencyRateExpression from './currency-rate-expression.vue';

import rateSourcesManager from '../api/exchange-sources/exchange-sources-manager.js'; // TODO: pass as props/context
import { Currency } from '../api/exchange-sources/exchange-rates-data-objects.js';

function convertCurrencyArrayToListItems(currencyArray) {
  return currencyArray?.map((item) => ({ value: item.CharCode, text: item.Name }));
}

function HandleValueNumberToZero(value) {
  if (Number.isNaN(value) || value === Infinity || value === undefined || value === null) {
    return 0;
  }
  return value;
}

const toggleIconSrc = require('@/assets/up-down-arrows.svg');

export default {
  components: { UiEditor, LabeledEditor, UiButton, LoadingPanel, CurrencyRateExpression },

  data() {
    return {
      toggleIconSrc: toggleIconSrc,
      availableCurrencies: [],
      availableCurrenciesListItems: [],
      amount: 4000,
      sourceCurrencyCharCode: 'USD',
      sourceCurrencyValue: null,
      targetCurrencyCharCode: 'RUB',
      targetCurrencyValue: null,
      targetAmount: 0,
      targetRate: 0,
      demoDataMessage: null,
      isLoading: false,
      exchangeRatesSourceKey: 'cbr',
      availableExchangeRateSources: rateSourcesManager
        .getRegisteredSources()
        .map((item) => ({ value: item.key, text: item.caption })),
      lastAbortController: null,
    };
  },

  methods: {
    handleTogglerClick() {
      const currentSourceCurrencyCharCode = this.sourceCurrencyCharCode;
      this.sourceCurrencyCharCode = this.targetCurrencyCharCode;
      this.targetCurrencyCharCode = currentSourceCurrencyCharCode;
    },
    refreshSourceCurrencyValue() {
      const newCurrency = this.availableCurrencies?.find((item) => item.CharCode === this.sourceCurrencyCharCode);
      this.sourceCurrencyValue = newCurrency?.Value;
    },
    refreshTargetCurrencyValue() {
      const newCurrency = this.availableCurrencies?.find((item) => item.CharCode === this.targetCurrencyCharCode);
      this.targetCurrencyValue = newCurrency?.Value;
    },
    refreshTargetAmount() {
      const safeValue = HandleValueNumberToZero((this.amount * this.sourceCurrencyValue) / this.targetCurrencyValue);
      this.targetAmount = Math.round((safeValue + Number.EPSILON) * 100) / 100;
    },
    refreshTargetRate() {
      const safeValue = HandleValueNumberToZero(this.sourceCurrencyValue / this.targetCurrencyValue);
      this.targetRate = Math.round((safeValue + Number.EPSILON) * 10000) / 10000;
    },
    refreshAvailableCurrenciesListItems() {
      this.availableCurrenciesListItems = convertCurrencyArrayToListItems(this.availableCurrencies);
    },
  },

  watch: {
    exchangeRatesSourceKey: {
      immediate: true,
      handler(newValue, _, onInvalidate) {
        this.isLoading = true;
        const currentAbortController = {};
        onInvalidate(() => (currentAbortController.aborted = true)); /* cancellationToken */
        rateSourcesManager
          .getRates(newValue)
          .then((exchangeRates) => {
            if (currentAbortController.aborted) {
              return;
            }
            this.availableCurrencies = exchangeRates?.Items;
            this.demoDataMessage = newValue === 'demo' ? 'Демо данные' : null;
            this.isLoading = false;
          })
          .catch((error) => {
            if (currentAbortController.aborted) {
              return;
            }
            const demoDataMessageTemplate =
              'При получении данных о курсе обмена валют возникла ошибка и показаны демонстрационные данные';
            this.isLoading = false;
            this.demoDataMessage = `${demoDataMessageTemplate} (${error})`;
            this.availableCurrencies = [Currency.RUB(), Currency.USD(), Currency.GBP()];
            this.sourceCurrencyCharCode = Currency.USD().CharCode;
            this.targetCurrencyCharCode = Currency.RUB().CharCode;
          });
      },
    },
    availableCurrencies: {
      immediate: true,
      handler() {
        this.refreshSourceCurrencyValue();
        this.refreshTargetCurrencyValue();
        this.refreshAvailableCurrenciesListItems();
        // Alternatives:
        // 1. watching multiple sources: "watch([firstName, lastName]..." (it is described at 'ru' only: https://v3.ru.vuejs.org/ru/guide/reactivity-computed-watchers.html)
        // 2. watch calculated property (don't like)
        // 3. watchEffect (requires migration to 'setup()' or '<script setup>')
      },
    },
    sourceCurrencyCharCode: {
      immediate: true,
      handler() {
        this.refreshSourceCurrencyValue();
      },
    },
    targetCurrencyCharCode: {
      immediate: true,
      handler() {
        this.refreshTargetCurrencyValue();
      },
    },
    amount: {
      immediate: true,
      handler() {
        this.refreshTargetAmount();
      },
    },
    sourceCurrencyValue: {
      immediate: true,
      handler() {
        this.refreshTargetAmount();
        this.refreshTargetRate();
      },
    },
    targetCurrencyValue: {
      immediate: true,
      handler() {
        this.refreshTargetAmount();
        this.refreshTargetRate();
      },
    },
  },
};
</script>

<style scoped>
.converter {
  display: flex;
  flex-direction: column;
  align-items: stretch;

  /* start new stacking context to use absolute for loading-panel */
  position: relative;
}

.converter__field-set {
  border: none;
  padding: 0;
  margin: 0;

  display: flex;
  flex-direction: column;
  align-items: stretch;
  gap: 30px;
}

.converter__currency-toggler {
  align-self: center;
}

.converter__demo-data-message {
  /* reset browser styles */
  padding: 0;
  margin: 0;

  position: absolute;
  left: 50%;
  bottom: 0;
  transform: translate(-50%, -20%);
  width: 100%;
  text-align: center;
  z-index: -1;

  color: red;
  font-size: 16px;
  font-weight: 700;
}

.converter__target-amount {
  /* reset browser styles */
  padding: 0;
  margin: 0;

  margin-top: 30px;

  text-align: center;

  font-style: normal;
  font-weight: 700;
  font-size: 30px;
}

.converter__values {
  border: none;
  padding: 0;
  margin: 0;

  display: flex;
  flex-direction: column;
  align-items: stretch;
  gap: 30px;
}
</style>

// react/src/components/Converter/Converter.js
import { Fragment, useEffect, useState } from 'react';
import Button from '../button/button';
import Editor from '../editor/editor';
import LabeledEditor from '../labeled-editor/labeled-editor';
import CurrencyRateExpression from '../currency-rate-expression/currency-rate-expression';
import { convertCurrenciesToSelectElementOptions } from './utils';
import { ReactComponent as UpDownArrowsSvg } from '../../images/up-down-arrows.svg'; /* from https://uxwing.com/up-down-arrows-icon/ */
import LoadingPanel from '../loading-panel/loading-panel';
import rateSourcesManager from '../../api/exchange-sources/exchange-sources-manager.js';

import { Currency } from '../../api/exchange-sources/exchange-rates-data-objects';

import styles from './converter.module.css';
import styles__currencyToggler from './__currency-toggler/converter__currency-toggler.module.css';
import styles__targetAmount from './__target-amount/converter__target-amount.module.css';
import styles__values from './__values/converter__values.module.css';
import styles__demoDataMessage from './__demo-data-message/converter__demo-data-message.module.css';

function Converter({
  classes,
  availableCurrencies,
  amount,
  amountChanged,
  sourceCurrencyCharCode,
  sourceCurrencyCharCodeChanged,
  targetCurrencyCharCode,
  targetCurrencyCharCodeChanged,
  targetAmount,
  targetRate,
  demoDataMessage,
  isLoading,
  exchangeRatesSourceKey,
  exchangeRatesSourceKeyChanged,
  availableExchangeRateSources }) {

  const selectCurrencyOptions = convertCurrenciesToSelectElementOptions(availableCurrencies).map(item => {
    return (<option key={ item.value } value={ item.value }>{ item.text }</option>);
  });

  const handleAmountChange = e => amountChanged(Number(e.target.value));
  const handleSourceCurrencyChange = e => sourceCurrencyCharCodeChanged(e.target.value);
  const handleTargetCurrencyChange = e => targetCurrencyCharCodeChanged(e.target.value);

  const handleTogglerClick = () => {
    const currentSourceCurrencyCharCode = sourceCurrencyCharCode;
    sourceCurrencyCharCodeChanged(targetCurrencyCharCode);
    targetCurrencyCharCodeChanged(currentSourceCurrencyCharCode);
  };

  const selectExchangeRatesSourceOptions = availableExchangeRateSources?.map(item => {
    return (<option key={ item.key } value={ item.key }>{ item.caption }</option>);
  });
  
  const handleExchangeRatesSourceChange = e => exchangeRatesSourceKeyChanged(e.target.value);

  return (
    <Fragment>
      <div className={ `${classes} ${styles.s}` }>
        <form onSubmit={ e => e.preventDefault() }>
          <fieldset className={ styles__values.s }>
            <Editor value={ amount } onInput={ handleAmountChange } type="number" required step="0.01" />
            <LabeledEditor caption="From">
              <Editor tagName="select" required value={ sourceCurrencyCharCode } onChange={ handleSourceCurrencyChange } >
                { selectCurrencyOptions }
              </Editor>
            </LabeledEditor>
            <Button classes={ styles__currencyToggler.s } onClick={ handleTogglerClick } svgImage={ UpDownArrowsSvg } text="Toggle currencies" />
            <LabeledEditor caption="Into">
              <Editor tagName="select" required value={ targetCurrencyCharCode } onChange={ handleTargetCurrencyChange } >
                { selectCurrencyOptions }
              </Editor>
            </LabeledEditor>
            <LabeledEditor caption="Exchange rates source">
              <Editor tagName="select" required value={ exchangeRatesSourceKey } onChange={ handleExchangeRatesSourceChange } >
                { selectExchangeRatesSourceOptions }
              </Editor>
            </LabeledEditor>
          </fieldset>
        </form>
        <p className={ styles__targetAmount.s }>{ targetAmount }</p>
        <CurrencyRateExpression
          sourceCurrencyCharCode={ sourceCurrencyCharCode }
          targetRate={ targetRate }
          targetCurrencyCharCode={ targetCurrencyCharCode } />
        { demoDataMessage && <p className={ styles__demoDataMessage.s }>{ demoDataMessage }</p> }
        { isLoading && <LoadingPanel /> }
      </div>
    </Fragment>
  );
}

function HandleValueNumberToZero(value) {
  if (Number.isNaN(value) || value === Infinity || value === undefined || value === null) {
    return 0;
  }
  return value;
}

function ConverterWrapper(props) {
  const [isLoading, setIsLoading] = useState(true);
  const [availableCurrencies, setAvailableCurrencies] = useState([]);
  const [amount, setAmount] = useState(4000);
  const [targetAmount, setTargetAmount] = useState(0);
  const [targetRate, setTargetRate] = useState(0);
  const [sourceCurrencyValue, setSourceCurrencyValue] = useState(0);
  const [sourceCurrencyCharCode, setSourceCurrencyCharCode] = useState(Currency.USD().CharCode);
  const [targetCurrencyValue, setTargetCurrencyValue] = useState(0);
  const [targetCurrencyCharCode, setTargetCurrencyCharCode] = useState(Currency.RUB().CharCode);
  const [exchangeRatesSourceKey, setExchangeRatesSourceKey] = useState('cbr');
  const [demoDataMessage, setDemoDataMessage] = useState();

  useEffect(
    () => {
      const currentAbortController = {};
      rateSourcesManager.getRates(exchangeRatesSourceKey)
        .then(exchangeRates => {
          if (currentAbortController.aborted) {
            return;
          }
          setAvailableCurrencies(exchangeRates?.Items);
          setDemoDataMessage(exchangeRatesSourceKey === 'demo' ? 'Демо данные' : null);
          setIsLoading(false);
        })
        .catch(error => {
          if (currentAbortController.aborted) {
            return;
          }
          const demoDataMessageTemplate = "При получении данных о курсе обмена валют возникла ошибка и показаны демонстрационные данные";
          setIsLoading(false);
          setDemoDataMessage(`${demoDataMessageTemplate} (${error})`);
          setAvailableCurrencies([Currency.RUB(), Currency.USD(), Currency.GBP()]);
          setSourceCurrencyCharCode(Currency.USD().CharCode);
          setSourceCurrencyValue(Currency.USD().Value);
          setTargetCurrencyCharCode(Currency.RUB().CharCode);
          setTargetCurrencyValue(Currency.RUB().Value);
        });
      return () => currentAbortController.aborted = true; /* cancellationToken */
    },
    [exchangeRatesSourceKey]
  );

  useEffect(() => {
    const newCurrency = availableCurrencies?.find(item => item.CharCode === sourceCurrencyCharCode);
    setSourceCurrencyValue(newCurrency?.Value);
  }, [availableCurrencies, sourceCurrencyCharCode]);

  useEffect(() => {
    const newCurrency = availableCurrencies?.find(item => item.CharCode === targetCurrencyCharCode);
    setTargetCurrencyValue(newCurrency?.Value);
  }, [availableCurrencies, targetCurrencyCharCode]);

  useEffect(() => {
    const safeValue = HandleValueNumberToZero(amount * sourceCurrencyValue / targetCurrencyValue);
    setTargetAmount(Math.round((safeValue + Number.EPSILON) * 100) / 100);
  }, [amount, sourceCurrencyValue, targetCurrencyValue]);

  useEffect(() => {
    const safeValue = HandleValueNumberToZero(sourceCurrencyValue / targetCurrencyValue);
    setTargetRate(Math.round((safeValue + Number.EPSILON) * 10000) / 10000);
  }, [sourceCurrencyValue, targetCurrencyValue]);

  const amountChanged = (value) => setAmount(HandleValueNumberToZero(value));

  const sourceCurrencyCharCodeChanged = (value) => {
    setSourceCurrencyCharCode(value);
  };

  const targetCurrencyCharCodeChanged = (value) => {
    setTargetCurrencyCharCode(value);
  };

  const exchangeRatesSourceKeyChanged = (value) => {
    setExchangeRatesSourceKey(value);
  }

  const availableExchangeRateSources = rateSourcesManager.getRegisteredSources().map(item => ({ key: item.key, caption: item.caption }))

  return (
    <Converter classes={ props.classes }
      amount={ amount }
      amountChanged={ amountChanged }
      sourceCurrencyValue={ sourceCurrencyValue }
      sourceCurrencyCharCode={ sourceCurrencyCharCode }
      sourceCurrencyCharCodeChanged={ sourceCurrencyCharCodeChanged }
      targetCurrencyValue={ targetCurrencyValue }
      targetCurrencyCharCode={ targetCurrencyCharCode }
      targetCurrencyCharCodeChanged={ targetCurrencyCharCodeChanged }
      targetAmount={ targetAmount }
      availableCurrencies={ availableCurrencies }
      targetRate={ targetRate }
      isLoading={ isLoading }
      availableExchangeRateSources={ availableExchangeRateSources }
      exchangeRatesSourceKey={ exchangeRatesSourceKey }
      exchangeRatesSourceKeyChanged={ exchangeRatesSourceKeyChanged }
      demoDataMessage={ demoDataMessage }
    />
  );
}

export default ConverterWrapper;
