// vue/src/components/converter-with-calculator/converter-with-calculator.vue
<template>
  <ConverterUI
    :selectCurrencyListItems="selectCurrencyListItems"
    v-model:amount="amount"
    v-model:sourceCurrencyCharCode="sourceCurrencyCharCode"
    v-model:targetCurrencyCharCode="targetCurrencyCharCode"
    :targetAmount="targetAmount"
    :targetRate="targetRate"
    :warningMessage="warningMessage"
    :isLoading="isLoading"
    v-model:exchangeRatesSourceKey="exchangeRatesSourceKeyComputed"
    :selectRatesSourceListItems="selectRatesSourceListItems"
  />
</template>

<script>
import ConverterUI from '../converter-ui/converter-ui.vue';

import { calculateTargetAmount, calculateTargetRate } from '../../api/currency-converter';

function handleIncorrectCharCode(charCode, availableCurrencies, defaultCharCode) {
  if (!charCode || !availableCurrencies?.find(item => item.CharCode === charCode)) {
    if (availableCurrencies?.find(item => item.CharCode === defaultCharCode)) {
      return defaultCharCode;
    }
    else if (availableCurrencies.length) {
      return availableCurrencies[0].CharCode;
    }
  }
  return charCode;
}

export default {
  components: { ConverterUI },

  props: {
    availableExchangeRateSources: {
      type: Array,
      validator: (items) =>
        items.every((item) => typeof item === 'object' && item !== null && 'key' in item && 'caption' in item),
    },
    exchangeRatesSourceKey: { type: String},

    availableCurrencies: {
      type: Array,
      validator: (items) =>
        items.every((item) => typeof item === 'object' && item !== null && 'CharCode' in item && 'Name' in item),
    },
    defaultSourceCurrencyCharCode: { type: String},
    defaultTargetCurrencyCharCode: { type: String},

    isLoading: { type: Boolean},
    warningMessage: { type: String},
  },

  data() {
    return {
      amount: 4000,
      sourceCurrencyCharCode: 'USD',
      targetCurrencyCharCode: 'RUB',
    };
  },

  computed: {
    selectRatesSourceListItems() {
      return this.availableExchangeRateSources.map((item) => ({ value: item.key, text: item.caption }));
    },
    exchangeRatesSourceKeyComputed: {
      get() {
        return this.exchangeRatesSourceKey;
      },
      set(newValue) {
        this.$emit('update:exchangeRatesSourceKey', newValue);
      },
    },
    selectCurrencyListItems() {
      return this.availableCurrencies?.map((item) => ({
        value: item.CharCode,
        text: item.Name + ` (${item.CharCode})`,
      }));
    },
    targetCurrencyValue() {
      const newCurrency = this.availableCurrencies?.find((item) => item.CharCode === this.targetCurrencyCharCode);
      return newCurrency?.Value;
    },
    sourceCurrencyValue() {
      const newCurrency = this.availableCurrencies?.find((item) => item.CharCode === this.sourceCurrencyCharCode);
      return newCurrency?.Value;
    },
    targetAmount() {
      return calculateTargetAmount(this.amount, this.sourceCurrencyValue, this.targetCurrencyValue);
    },
    targetRate() {
      return calculateTargetRate(this.sourceCurrencyValue, this.targetCurrencyValue);
    },
  },

  watch: {
    availableCurrencies: {
      immediate: true,
      handler(newValue) {
        // value depends on [sourceCurrencyCharCode, availableCurrencies, defaultSourceCurrencyCharCode]
        this.sourceCurrencyCharCode = handleIncorrectCharCode(this.sourceCurrencyCharCode, newValue, this.defaultSourceCurrencyCharCode);
        this.sourceCurrencyCharCode = handleIncorrectCharCode(this.sourceCurrencyCharCode, newValue, this.defaultSourceCurrencyCharCode);
      }
    }
  },
};
</script>

<style scoped></style>

// react/src/components/converter-with-calculator/converter-with-calculator.js
import { useCallback, useEffect, useState, useMemo } from 'react';
import ConverterUI from '../converter-ui/converter-ui.js';

import { calculateTargetAmount, calculateTargetRate } from '../../api/currency-converter';
import { HandleValueNumberToZero } from '../../api/utils';
import { convertCurrenciesToSelectListItems } from './utils';

function handleIncorrectCharCode(charCode, availableCurrencies, defaultCharCode) {
  if (!charCode || !availableCurrencies?.find(item => item.CharCode === charCode)) {
    if (availableCurrencies?.find(item => item.CharCode === defaultCharCode)) {
      return defaultCharCode;
    }
    else if (availableCurrencies.length) {
      return availableCurrencies[0].CharCode;
    }
  }
  return charCode;
}

function ConverterWithCalculator({
  classes,
  availableExchangeRateSources,
  exchangeRatesSourceKey,
  isLoading,
  warningMessage,
  availableCurrencies,
  exchangeRatesSourceKeyChanged,
  defaultSourceCurrencyCharCode,
  defaultTargetCurrencyCharCode }) {

  const [amount, setAmount] = useState(4000);
  const [targetAmount, setTargetAmount] = useState(0);
  const [targetRate, setTargetRate] = useState(0);
  const [sourceCurrencyValue, setSourceCurrencyValue] = useState(0);
  const [sourceCurrencyCharCode, setSourceCurrencyCharCode] = useState();
  const [targetCurrencyValue, setTargetCurrencyValue] = useState(0);
  const [targetCurrencyCharCode, setTargetCurrencyCharCode] = useState();

  useEffect(() => {
    setSourceCurrencyCharCode(handleIncorrectCharCode(sourceCurrencyCharCode, availableCurrencies, defaultSourceCurrencyCharCode));
  }, [sourceCurrencyCharCode, availableCurrencies, defaultSourceCurrencyCharCode]);

  useEffect(() => {
    setTargetCurrencyCharCode(handleIncorrectCharCode(targetCurrencyCharCode, availableCurrencies, defaultTargetCurrencyCharCode));
  }, [targetCurrencyCharCode, availableCurrencies, defaultTargetCurrencyCharCode]);

  useEffect(() => {
    const newCurrency = availableCurrencies?.find(item => item.CharCode === sourceCurrencyCharCode);
    setSourceCurrencyValue(newCurrency?.Value);
  }, [availableCurrencies, sourceCurrencyCharCode]);

  useEffect(() => {
    const newCurrency = availableCurrencies?.find(item => item.CharCode === targetCurrencyCharCode);
    setTargetCurrencyValue(newCurrency?.Value);
  }, [availableCurrencies, targetCurrencyCharCode]);

  useEffect(() => {
    const newValue = calculateTargetAmount(amount, sourceCurrencyValue, targetCurrencyValue);
    setTargetAmount(newValue);
  }, [amount, sourceCurrencyValue, targetCurrencyValue]);

  useEffect(() => {
    const newValue = calculateTargetRate(sourceCurrencyValue, targetCurrencyValue);
    setTargetRate(newValue);
  }, [sourceCurrencyValue, targetCurrencyValue]);

  const amountChanged = useCallback(value => setAmount(HandleValueNumberToZero(value)), []);
  const sourceCurrencyCharCodeChanged = useCallback(value => setSourceCurrencyCharCode(value), []);
  const targetCurrencyCharCodeChanged = useCallback(value => setTargetCurrencyCharCode(value), []);

  const selectCurrencyListItems = useMemo(
    () => convertCurrenciesToSelectListItems(availableCurrencies),
    [availableCurrencies]);
  
  const selectRatesSourceListItems = useMemo(
    () => availableExchangeRateSources?.map(item => ({ value: item.key, text: item.caption })),
    [availableExchangeRateSources]);


  return (
    <ConverterUI classes={ classes }
      amount={ amount }
      amountChanged={ amountChanged }
      sourceCurrencyValue={ sourceCurrencyValue }
      sourceCurrencyCharCode={ sourceCurrencyCharCode }
      sourceCurrencyCharCodeChanged={ sourceCurrencyCharCodeChanged }
      targetCurrencyValue={ targetCurrencyValue }
      targetCurrencyCharCode={ targetCurrencyCharCode }
      targetCurrencyCharCodeChanged={ targetCurrencyCharCodeChanged }
      targetAmount={ targetAmount }
      selectCurrencyListItems={ selectCurrencyListItems }
      targetRate={ targetRate }
      isLoading={ isLoading }
      selectRatesSourceListItems={ selectRatesSourceListItems }
      exchangeRatesSourceKey={ exchangeRatesSourceKey }
      exchangeRatesSourceKeyChanged={ exchangeRatesSourceKeyChanged }
      warningMessage={ warningMessage }
    />
  );
}

export default ConverterWithCalculator;
