// vue/src/components/converter-ui/converter-ui.vue
<template>
  <div v-bind="$attrs" class="converter">
    <form @submit.prevent>
      <fieldset class="converter__values">
        <UiEditor aria-label="Source amount" editorType="spinbutton" v-model="amountComputed" required :step="0.01" />
        <LabeledEditor caption="From">
          <UiEditor
            editorType="combobox"
            v-model="sourceCurrencyCharCodeComputed"
            required
            :listItems="selectCurrencyListItemsSorted"
          />
        </LabeledEditor>
        <UiButton
          class="converter__currency-toggler"
          :image="toggleIconSrc"
          text="Toggle currencies"
          @click="() => handleTogglerClick()"
        />
        <LabeledEditor caption="Into">
          <UiEditor
            editorType="combobox"
            v-model="targetCurrencyCharCodeComputed"
            required
            :listItems="selectCurrencyListItemsSorted"
          />
        </LabeledEditor>
        <LabeledEditor caption="Exchange rates source">
          <UiEditor
            editorType="combobox"
            v-model="exchangeRatesSourceKeyComputed"
            required
            :listItems="selectRatesSourceListItems"
          />
        </LabeledEditor>
      </fieldset>
    </form>
    <p aria-label="Target amount" class="converter__target-amount">{{ targetAmount }}</p>
    <CurrencyRateExpression
      :sourceCurrencyCharCode="sourceCurrencyCharCode"
      :targetRate="targetRate"
      :targetCurrencyCharCode="targetCurrencyCharCode"
    />
    <p v-if="warningMessage" aria-label="Warning message" class="converter__warning-message">{{ warningMessage }}</p>
    <LoadingPanel v-if="isLoading" data-testid="loading-panel" />
  </div>
</template>

<script>
import UiEditor from '../ui-editor/ui-editor.vue';
import LabeledEditor from '../labeled-editor/labeled-editor.vue';
import UiButton from '../ui-button/ui-button.vue';
import LoadingPanel from '../loading-panel/loading-panel.vue';
import CurrencyRateExpression from '../currency-rate-expression/currency-rate-expression.vue';
import { Currency } from '../../api/exchange-sources/exchange-rates-data-objects.js';

const toggleIconSrc = require('@/assets/up-down-arrows.svg');

export default {
  components: { UiEditor, LabeledEditor, UiButton, LoadingPanel, CurrencyRateExpression },

  props: {
    selectCurrencyListItems: { type: Array, default: [] },
    amount: { type: Number, default: 0 },
    sourceCurrencyCharCode: { type: String },
    targetCurrencyCharCode: { type: String },
    targetAmount: { type: Number, default: 0 },
    targetRate: { type: Number, default: 0 },
    warningMessage: { type: String },
    isLoading: { type: Boolean },
    exchangeRatesSourceKey: { type: [String] },
    selectRatesSourceListItems: { type: Array, default: [] },
  },

  emits: [
    'update:amount',
    'update:sourceCurrencyCharCode',
    'update:targetCurrencyCharCode',
    'update:exchangeRatesSourceKey',
  ],

  data() {
    return {
      toggleIconSrc: toggleIconSrc,
    };
  },

  computed: {
    amountComputed: {
      get() {
        return this.amount;
      },
      set(newValue) {
        this.$emit('update:amount', newValue);
      },
    },
    sourceCurrencyCharCodeComputed: {
      get() {
        return this.sourceCurrencyCharCode;
      },
      set(newValue) {
        this.$emit('update:sourceCurrencyCharCode', newValue);
      },
    },
    targetCurrencyCharCodeComputed: {
      get() {
        return this.targetCurrencyCharCode;
      },
      set(newValue) {
        this.$emit('update:targetCurrencyCharCode', newValue);
      },
    },
    exchangeRatesSourceKeyComputed: {
      get() {
        return this.exchangeRatesSourceKey;
      },
      set(newValue) {
        this.$emit('update:exchangeRatesSourceKey', newValue);
      },
    },
    selectCurrencyListItemsSorted() {
      const RUB = Currency.RUB().CharCode;
      return this.selectCurrencyListItems
        ?.sort((a, b) => {
          if (a.value === RUB) {
            return -1;
          } else if (b.value === RUB) {
            return 1;
          }
          return a.text > b.text ? 1 : -1;
        });
    },
  },

  methods: {
    handleTogglerClick() {
      const currentSourceCurrencyCharCode = this.sourceCurrencyCharCode;
      this.$emit('update:sourceCurrencyCharCode', this.targetCurrencyCharCode);
      this.$emit('update:targetCurrencyCharCode', currentSourceCurrencyCharCode);
    },
  },

  watch: {},
};
</script>

<style scoped>
.converter {
  display: flex;
  flex-direction: column;
  align-items: stretch;

  /* start new stacking context to use absolute for loading-panel */
  position: relative;
}

.converter__field-set {
  border: none;
  padding: 0;
  margin: 0;

  display: flex;
  flex-direction: column;
  align-items: stretch;
  gap: 30px;
}

.converter__currency-toggler {
  align-self: center;
}

.converter__warning-message {
  /* reset browser styles */
  padding: 0;
  margin: 0;

  position: absolute;
  left: 50%;
  bottom: 0;
  transform: translate(-50%, -20%);
  width: 100%;
  text-align: center;
  z-index: -1;

  color: red;
  font-size: 16px;
  font-weight: 700;
}

.converter__target-amount {
  /* reset browser styles */
  padding: 0;
  margin: 0;

  margin-top: 30px;

  text-align: center;

  font-style: normal;
  font-weight: 700;
  font-size: 30px;
}

.converter__values {
  border: none;
  padding: 0;
  margin: 0;

  display: flex;
  flex-direction: column;
  align-items: stretch;
  gap: 30px;
}
</style>

// react/src/components/converter-ui/converter-ui.js
import { useCallback, useMemo } from 'react';
import Button from '../button/button';
import Editor from '../editor/editor';
import LabeledEditor from '../labeled-editor/labeled-editor';
import CurrencyRateExpression from '../currency-rate-expression/currency-rate-expression';
import { ReactComponent as UpDownArrowsSvg } from '../../images/up-down-arrows.svg'; /* from https://uxwing.com/up-down-arrows-icon/ */
import LoadingPanel from '../loading-panel/loading-panel';
import { Currency } from '../../api/exchange-sources/exchange-rates-data-objects';

import styles from './converter-ui.module.css';
import styles__currencyToggler from './__currency-toggler/converter-ui__currency-toggler.module.css';
import styles__targetAmount from './__target-amount/converter-ui__target-amount.module.css';
import styles__values from './__values/converter-ui__values.module.css';
import styles__warningMessage from './__warning-message/converter-ui__warning-message.module.css';

function ConverterUI({
  classes,
  selectCurrencyListItems,
  amount,
  amountChanged,
  sourceCurrencyCharCode,
  sourceCurrencyCharCodeChanged,
  targetCurrencyCharCode,
  targetCurrencyCharCodeChanged,
  targetAmount,
  targetRate,
  warningMessage,
  isLoading,
  exchangeRatesSourceKey,
  exchangeRatesSourceKeyChanged,
  selectRatesSourceListItems }) {

  const handleAmountChange = useCallback(e => amountChanged(Number(e.target.value)), [amountChanged]);
  const handleSourceCurrencyChange = useCallback(e => sourceCurrencyCharCodeChanged(e.target.value), [sourceCurrencyCharCodeChanged]);
  const handleTargetCurrencyChange = useCallback(e => targetCurrencyCharCodeChanged(e.target.value), [targetCurrencyCharCodeChanged]);

  const handleTogglerClick = useCallback(() => {
    const currentSourceCurrencyCharCode = sourceCurrencyCharCode;
    sourceCurrencyCharCodeChanged?.(targetCurrencyCharCode);
    targetCurrencyCharCodeChanged?.(currentSourceCurrencyCharCode);
  }, [sourceCurrencyCharCode, sourceCurrencyCharCodeChanged, targetCurrencyCharCode, targetCurrencyCharCodeChanged]);

  const handleExchangeRatesSourceChange = e => exchangeRatesSourceKeyChanged(e.target.value);

  const sortedSelectCurrencyListItems = useMemo(() => {
    const RUB = Currency.RUB().CharCode;
    return (selectCurrencyListItems || [])
      .sort((a, b) => {
        if (a.value === RUB) {
          return -1;
        }
        else if (b.value === RUB) {
          return 1;
        }

        return ((a.text > b.text) ? 1 : -1);
      });
  }, [selectCurrencyListItems]);

  return (
    <div className={ `${classes} ${styles.s}` }>
      <form onSubmit={ e => e.preventDefault() }>
        <fieldset className={ styles__values.s }>
          <Editor
            aria-label="Source amount" // this text is not visible but it is obvious
            value={ amount } onInput={ handleAmountChange } type="number" required step="0.01" />
          <LabeledEditor caption="From">
            <Editor tagName="select" required value={ sourceCurrencyCharCode } onChange={ handleSourceCurrencyChange } listItems={ sortedSelectCurrencyListItems } />
          </LabeledEditor>
          <Button classes={ styles__currencyToggler.s } onClick={ handleTogglerClick } svgImage={ UpDownArrowsSvg } text="Toggle currencies" />
          <LabeledEditor caption="Into">
            <Editor tagName="select" required value={ targetCurrencyCharCode } onChange={ handleTargetCurrencyChange } listItems={ sortedSelectCurrencyListItems } />
          </LabeledEditor>
          <LabeledEditor caption="Exchange rates source">
            <Editor tagName="select" required value={ exchangeRatesSourceKey } onChange={ handleExchangeRatesSourceChange } listItems={ selectRatesSourceListItems } />
          </LabeledEditor>
        </fieldset>
      </form>
      <p
        aria-label="Target amount"
        className={ styles__targetAmount.s }>{ targetAmount }</p>
      <CurrencyRateExpression
        sourceCurrencyCharCode={ sourceCurrencyCharCode }
        targetRate={ targetRate }
        targetCurrencyCharCode={ targetCurrencyCharCode } />
      { warningMessage && <p aria-label="Warning message" className={ styles__warningMessage.s }>{ warningMessage }</p> }
      { isLoading && <LoadingPanel data-testid="loading-panel" /> }
    </div>
  );
}

export default ConverterUI;
